// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StageCase.Infra.Data;

#nullable disable

namespace StageCase.Infra.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241017204623_CreateDataBase")]
    partial class CreateDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StageCase.Domain.Entities.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("IdProcessParent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("IdProcessParent");

                    b.ToTable("Process");
                });

            modelBuilder.Entity("StageCase.Domain.Entities.Process", b =>
                {
                    b.HasOne("StageCase.Domain.Entities.Process", "ProcessParent")
                        .WithMany("SubProcesses")
                        .HasForeignKey("IdProcessParent")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("ProcessParent");
                });

            modelBuilder.Entity("StageCase.Domain.Entities.Process", b =>
                {
                    b.Navigation("SubProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
